/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookapp20.gui;

import bookapp20.Datasource;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author hover
 */
public class MainFrame extends javax.swing.JFrame {

    private final AddPublisherFrame addPublisherFrame = new AddPublisherFrame();
    private final AddAuthorFrame addAuthorFrame = new AddAuthorFrame();
    private final AddBookFrame addBookFrame = new AddBookFrame();
    private final AddCopyFrame addCopyFrame = new AddCopyFrame();
    private final ManageStudentFrame manageStudentFrame = new ManageStudentFrame();
    private final BorrowBookFrame manageBorrowFrame = new BorrowBookFrame();
    private final ReturnBookFrame returnBookFrame = new ReturnBookFrame();

    public MainFrame() {
        initComponents();
        setIcon();
        desk.add(addPublisherFrame);
        desk.add(addAuthorFrame);
        desk.add(addBookFrame);
        desk.add(addCopyFrame);
        desk.add(manageStudentFrame);
        desk.add(manageBorrowFrame);
        desk.add(returnBookFrame);
        initActions();
    }

    private void initActions() {

    }

    private void setIcon() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/icons8_library_16px.png"));
        this.setIconImage(icon.getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        publisherBtn = new javax.swing.JButton();
        authorBtn = new javax.swing.JButton();
        bookBtn = new javax.swing.JButton();
        copyBtn = new javax.swing.JButton();
        studentBtn = new javax.swing.JButton();
        borrowBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        desk = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Manager");
        setSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        publisherBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_leanpub_32px.png"))); // NOI18N
        publisherBtn.setToolTipText("Add New Publisher");
        publisherBtn.setFocusPainted(false);
        publisherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherBtnActionPerformed(evt);
            }
        });

        authorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_teacher_32px.png"))); // NOI18N
        authorBtn.setToolTipText("Add New Author");
        authorBtn.setFocusPainted(false);
        authorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorBtnActionPerformed(evt);
            }
        });

        bookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_book_32px_3.png"))); // NOI18N
        bookBtn.setToolTipText("Add New Book");
        bookBtn.setFocusPainted(false);
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        copyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_new_copy_32px.png"))); // NOI18N
        copyBtn.setToolTipText("Add New Copy");
        copyBtn.setFocusPainted(false);
        copyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyBtnActionPerformed(evt);
            }
        });

        studentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_students_32px.png"))); // NOI18N
        studentBtn.setToolTipText("Manage Students");
        studentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBtnActionPerformed(evt);
            }
        });

        borrowBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_borrow_book_32px.png"))); // NOI18N
        borrowBtn.setToolTipText("Borrow Books");
        borrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBtnActionPerformed(evt);
            }
        });

        returnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_return_book_32px_2.png"))); // NOI18N
        returnBtn.setToolTipText("Return Books");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publisherBtn)
                    .addComponent(authorBtn)
                    .addComponent(bookBtn)
                    .addComponent(copyBtn)
                    .addComponent(studentBtn)
                    .addComponent(borrowBtn)
                    .addComponent(returnBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {authorBtn, bookBtn, copyBtn, publisherBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(publisherBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrowBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnBtn)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        desk.setBackground(new java.awt.Color(204, 204, 204));
        desk.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        getContentPane().add(desk, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void publisherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherBtnActionPerformed
        if (addPublisherFrame.isVisible()) {
            desk.moveToFront(addPublisherFrame);
            try {
                addPublisherFrame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            return;
        }
        addPublisherFrame.setVisible(true);
        addPublisherFrame.reset();
    }//GEN-LAST:event_publisherBtnActionPerformed

    private void authorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorBtnActionPerformed
        if (addAuthorFrame.isVisible()) {
            desk.moveToFront(addAuthorFrame);
            try {
                addAuthorFrame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            return;
        }
        addAuthorFrame.setVisible(true);
        addAuthorFrame.reset();
    }//GEN-LAST:event_authorBtnActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        if (addBookFrame.isVisible()) {
            desk.moveToFront(addBookFrame);
            try {
                addBookFrame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            return;
        }
        addBookFrame.setVisible(true);
        addBookFrame.reset();
    }//GEN-LAST:event_bookBtnActionPerformed

    private void copyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyBtnActionPerformed
        if (addCopyFrame.isVisible()) {
            desk.moveToFront(addCopyFrame);
            try {
                addCopyFrame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            return;
        }
        addCopyFrame.setVisible(true);
        addCopyFrame.reset();
    }//GEN-LAST:event_copyBtnActionPerformed

    private void studentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBtnActionPerformed
        if (manageStudentFrame.isVisible()) {
            desk.moveToFront(manageStudentFrame);
            try {
                manageStudentFrame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            return;
        }
        manageStudentFrame.setVisible(true);
        manageStudentFrame.reset();

    }//GEN-LAST:event_studentBtnActionPerformed

    private void borrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBtnActionPerformed
        if (manageBorrowFrame.isVisible()) {
            desk.moveToFront(manageBorrowFrame);
            try {
                manageBorrowFrame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            return;
        }
        manageBorrowFrame.setVisible(true);
        manageBorrowFrame.reset();
    }//GEN-LAST:event_borrowBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        if (returnBookFrame.isVisible()) {
            desk.moveToFront(returnBookFrame);
            try {
                returnBookFrame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            return;
        }
        returnBookFrame.setVisible(true);
        returnBookFrame.reset();
    }//GEN-LAST:event_returnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        System.setProperty("log4j.configurationFile", "bookapp20/conf/log4j2.properties");

        new Thread(new Runnable() {
            @Override
            public void run() {
                Datasource.getConnection();
            }
        }).start();

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorBtn;
    private javax.swing.JButton bookBtn;
    private javax.swing.JButton borrowBtn;
    private javax.swing.JButton copyBtn;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton publisherBtn;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton studentBtn;
    // End of variables declaration//GEN-END:variables
}
